# packages/python/scripts/generate_models.py
"""Generate Pydantic v2 models from the AEP JSON Schema bundle."""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PACKAGE_DIR = HERE.parent
SCHEMA_DIR = PACKAGE_DIR.parent.parent / "docs" / "protocol" / "schemas"
OUT_FILE = PACKAGE_DIR / "helix_sdk" / "models" / "generated.py"

BUNDLE_FILES = [
    "enums.schema.json",
    "resources.schema.json",
    "events.schema.json",
    "rpc.schema.json",
]


def main() -> int:
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    header = [
        "# AUTOGENERATED - do not edit by hand. Regenerate via `uv run python scripts/generate_models.py`.",
        "# Source: docs/protocol/schemas/",
        "from __future__ import annotations",
        "",
    ]
    OUT_FILE.write_text("\n".join(header) + "\n", encoding="utf-8")

    for schema in BUNDLE_FILES:
        tmp = OUT_FILE.with_suffix(f".{schema}.tmp.py")
        cmd = [
            "datamodel-codegen",
            "--input", str(SCHEMA_DIR / schema),
            "--input-file-type", "jsonschema",
            "--output", str(tmp),
            "--output-model-type", "pydantic_v2.BaseModel",
            "--use-standard-collections",
            "--use-union-operator",
            "--target-python-version", "3.11",
            "--field-constraints",
            "--use-schema-description",
            "--use-default",
        ]
        print(f"[codegen] {schema}")
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(result.stdout)
            print(result.stderr, file=sys.stderr)
            return result.returncode

        generated = tmp.read_text(encoding="utf-8")
        # Strip the per-file header that datamodel-codegen adds and any duplicate imports.
        # The bundle header already declares `from __future__ import annotations`; the per-file
        # repeats would land mid-file and raise SyntaxError, so drop them here.
        stripped = "\n".join(
            line for line in generated.splitlines()
            if not line.startswith("# generated by datamodel-codegen")
            and not line.startswith("#   filename:")
            and not line.startswith("#   timestamp:")
            and not line.startswith("from __future__ import annotations")
        )
        with OUT_FILE.open("a", encoding="utf-8") as fh:
            fh.write(f"\n\n# --- {schema} ---\n")
            fh.write(stripped)
        tmp.unlink()

    print(f"Wrote {OUT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
