// packages/typescript/scripts/generate-types.ts
import { compileFromFile } from "json-schema-to-typescript";
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const SCHEMA_DIR = resolve(import.meta.dir, "../../../docs/protocol/schemas");
const OUT_FILE = resolve(import.meta.dir, "../src/types/generated.ts");

const BUNDLE_FILES = [
  "enums.schema.json",
  "resources.schema.json",
  "events.schema.json",
  "rpc.schema.json",
];

async function main() {
  const chunks: string[] = [
    "// AUTOGENERATED — do not edit by hand. Regenerate via `bun run generate`.",
    "// Source: docs/protocol/schemas/",
    "",
  ];

  for (const file of BUNDLE_FILES) {
    const full = resolve(SCHEMA_DIR, file);
    const ts = await compileFromFile(full, {
      cwd: SCHEMA_DIR,
      bannerComment: "",
      additionalProperties: false,
      unreachableDefinitions: true,
      style: { singleQuote: false },
    });
    chunks.push(`// --- ${file} ---`);
    chunks.push(ts);
    chunks.push("");
  }

  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, chunks.join("\n"), "utf8");
  console.log(`Wrote ${OUT_FILE}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
